[package]
authors = ["timotree3 <timorcb@gmail.com>"]
name = "rlinksdown"
version = "0.1.0"

[dependencies]
clap = "2.27.1"
error-chain = "0.11.0"
reqwest = "0.8.1"

[dependencies.pulldown-cmark]
default-features = false
version = "0.1.0"
